Adding menu
LM1398/tdd_vending_machine pull request #16
Opened 2021-09-27 14:10 UTC by LM1398

returnされるのがsetでも大丈夫でしょうか？もしprintの方が良かったら改良します！

2021-09-27 22:48 UTC, atsushimemet requested changes
よくできてます!
ただ現状の実装は、fridgeに入っているドリンクのセットです。
すなわち、在庫の点で購入可能なドリンクのセットです。
つまり投入金額、在庫の点で購入可能なドリンクのリストになっていないのです。

次は、投入金額を入れて、購入可能なドリンクのリストを取り出すところを考えてみましょう。

2021-09-28 04:23 UTC, atsushimemet approved these changes
@LM1398 
素晴らしいです。printデバッグを削除して、マージしてしまいましょう。

2021-09-28 04:23 UTC, atsushimemet commented on tests/vending_machine/test_purchasable.py
> +    print(vending_machine.purchasable())
@LM1398 
このprintデバッグは削除しましょう。

2021-09-28 04:42 UTC, LM1398 commented on tests/vending_machine/test_purchasable.py
> +    print(vending_machine.purchasable())
修正しました！

2021-09-28 04:42 UTC, merged