Adding vending machine simulator prototype
LM1398/tdd_vending_machine pull request #19
Opened 2021-09-29 03:00 UTC by LM1398

# 機能概要
- 簡単な自販機をinputで使用できる
- vending_machine.pyを通して稼働する
- 飲み物を購入できる
- 在庫を確認できる
- 合計売り上げが確認できる

# 機能を作成した目的
- とりあえずは vending_machine.pyで書いたコードを元に自販機が作れるのがどうか気になったから作ってみた
- 飲み物の購入は消費者用の機能
- stockとrevenueの確認は業者用の機能

# 実装における不安な点
- 飲み物を購入すると終わってしまう　（どうにかループにして最初のメニュー画面に戻ってほしい
- それをやった上で、exitという機能を作りたい
- 見た目が平凡
- 機能が少ない

# 改善の余地がある箇所
- full_vending_machine.pyの34行目 ~50行目
- もっと綺麗にまとめられると思う
- 正直改善点はあまりないが足せる機能が多い
- 例：メインメニューに戻る
- 例：受け付けないお金をちゃんと返金してそのタイプのお金は受け付けないと言う
- 例：消費者と業者の機能をどうにか分ける　(e.g. メニューで何か書くと実は業者用機能が出てくる

2021-09-29 14:05 UTC, atsushimemet requested changes
@LM1398 
コメントを見て、修正すべき部分は修正してください。

PRのドキュメントが素晴らしく、これを毎日続けられれば、大変素晴らしいです。

2021-09-29 14:05 UTC, atsushimemet commented on full_vending_machine.py
> +print("3. Check stock")
@LM1398 
print("A", "B", "C", sep="\n")とすれば、1行で書けるかなと思いました。

2021-09-29 14:05 UTC, atsushimemet commented on full_vending_machine.py
> +        selected = redbull
@LM1398 
関数にして良いかもしれません。

2021-09-29 14:05 UTC, atsushimemet commented on full_vending_machine.py
> +    print("")
@LM1398 
print関数のsepを使いましょう。

2021-09-29 14:05 UTC, atsushimemet commented on full_vending_machine.py
> +            vending_machine.insert(Money.M_10)
@LM1398 
関数で書きましょう。insert_moneyなど。

2021-09-30 11:11 UTC, LM1398 commented on full_vending_machine.py
> +print("3. Check stock")
修正しました！

2021-09-30 11:18 UTC, LM1398 commented on full_vending_machine.py
> +        selected = redbull
何でもっと早く思い付かなかったんでしょう！修正しました

2021-09-30 11:26 UTC, LM1398 commented on full_vending_machine.py
> +            vending_machine.insert(Money.M_10)
修正しました！

2021-09-30 11:39 UTC, atsushimemet approved these changes
@LM1398 
これもマージしてください。
そしてこれからどんなPRを上げるにせよ、このレベルのPRをあげてください。
素晴らしいPRでした。

2021-09-30 11:41 UTC, merged